const IS_LOADING = "IS_LOADING";
const ERROR = "ERROR";

const SET_CURRENT_USER = "SET_CURRENT_USER";

const SET_WALLET = "SET_WALLET";

const ADD_CARD = "ADD_CARD";
const UPDATE_CARD = "UPDATE_CARD";
const REMOVE_CARD = "REMOVE_CARD";

export default {
  SET_CURRENT_USER,
  IS_LOADING,
  ERROR,
  SET_WALLET,
  ADD_CARD,
  UPDATE_CARD,
  REMOVE_CARD
};
